---
title: "DEC Dashboard"
author: "Taylor Mack"
date: "3/10/2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(shinydashboard)
library(tidyverse)
library(ggplot2)
library(stringr)
library(ggiraph)
library(treemap)
library(d3treeR)
user_path <- "/Users/taylor/Documents/OMSBA 5210/DEC/OMSBA-5210-DEC"


game_reviews <- read.csv(paste0(user_path,"/Data/game_reviews.csv"))
global_sales <- read.csv(paste0(user_path,"/Data/global_sales.csv"))
pc_game_sales <- read.csv(paste0(user_path,"/Data/pc_game_sales.csv"))
twitch_game_data <- read.csv(paste0(user_path,"/Data/twitch_game_data.csv"))
twitch_global_data <- read.csv(paste0(user_path,"/Data/twitch_global_data.csv"))

data_set <- merge(x=global_sales,y=game_reviews,by.x="Name",by.y="name")

options(scipen = 999)

game_reviews_temp <- game_reviews %>% mutate(user_review = as.numeric(user_review) * 10) %>%
                                      mutate(platform = str_trim(platform)) %>%
                                      mutate(name = str_trim(name)) %>% drop_na()

global_sales_temp <- global_sales %>% filter(Year >= 2010) %>% filter(Year != "N/A") %>% 
                     mutate(handheld_console = 
                        ifelse(Platform %in% c("DS","3DS","PSP","PSV","GB"),TRUE,FALSE)) %>%
                     mutate(NA_Sales = NA_Sales * 1000000) %>%
                     mutate(EU_Sales = EU_Sales * 1000000) %>%
                     mutate(JP_Sales = JP_Sales * 1000000) %>%
                     mutate(Other_Sales = Other_Sales * 1000000) %>%
                     mutate(Global_Sales = Global_Sales * 1000000) %>%
                     mutate(Platform = case_when(
                       Platform == "X360" ~ "Xbox 360",
                       Platform == "PS3" ~ "PlayStation 3",
                       Platform == "PS4" ~ "PlayStation 4",
                       Platform == "XOne" ~ "Xbox One",
                       Platform == "WiiU" ~ "Wii U",
                       Platform == "PS2" ~ "PlayStation 2",
                       Platform == "GBA" ~ "Game Boy Advance",
                       Platform == "PSV" ~ "PlayStation Vita",
                       Platform == "PS" ~ "PlayStation",
                       Platform == "XB" ~ "Xbox",
                       Platform == "GC" ~ "GameCube",
                       Platform == "GB" ~ "Game Boy",
                       Platform == "GC" ~ "GameCube",
                       Platform == "N64" ~ "Nintendo 64",
                       TRUE ~ Platform
                     )) %>% mutate(Name = str_trim(Name)) %>% drop_na(c(Year,Platform))
twitch_game_data_temp <- twitch_game_data %>% mutate(Game = str_trim(Game)) %>%
                         filter(Game != "") %>%
                         mutate(Hours_watched = as.numeric(str_trim(sub("\\(.*","",Hours_watched)))) %>%
                         mutate(Hours_Streamed = str_trim(sub("\\(.*","",Hours_Streamed))) %>%
                         mutate(Peak_viewers = str_trim(sub("\\(.*","",Peak_viewers))) %>%
                         mutate(Peak_channels = str_trim(sub("\\(.*","",Peak_channels))) %>%
                         mutate(Streamers = str_trim(sub("\\(.*","",Streamers))) %>%
                         mutate(Avg_viewers = str_trim(sub("\\(.*","",Avg_viewers))) %>%
                         mutate(Avg_channels = str_trim(sub("\\(.*","",Avg_channels))) %>%
                         mutate(Avg_viewer_ratio = str_trim(sub("\\(.*","",Avg_viewer_ratio))) %>%
                         mutate(Hours_Streamed = as.numeric(gsub("\\D","",Hours_Streamed))) %>%
                         group_by(Game) %>% 
                         mutate(total_hours_watched = sum(Hours_watched)) %>%
                         mutate(total_hours_streamed = sum(as.numeric(Hours_Streamed))) %>%
                         mutate(avg_peak_viewers = mean(as.numeric(Peak_viewers))) %>%
                         mutate(avg_peak_channels = mean(as.numeric(Peak_channels))) %>%
                         mutate(avg_streamers = mean(as.numeric(Streamers))) %>%
                         mutate(Avg_viewers = mean(as.numeric(Avg_viewers))) %>%
                         mutate(Avg_channels = mean(as.numeric(Avg_channels))) %>%
                         mutate(Avg_viewer_ratio = mean(as.numeric(Avg_viewer_ratio))) %>%
                         select(c("Game","total_hours_watched","total_hours_streamed",
                                  "avg_peak_viewers","avg_peak_channels","avg_streamers","Avg_viewers",
                                  "Avg_channels","Avg_viewer_ratio")) %>% unique() %>% ungroup()

data_set <- left_join(x=global_sales_temp,y=game_reviews_temp,by=c("Name"="name","Platform"="platform"))
data_set <- left_join(x=data_set,y=twitch_game_data_temp,by=c("Name"="Game"))

regression_data_set <- data_set %>% select(-c("Platform","Rank")) %>% unique() %>%
                       drop_na(meta_score,user_review) %>% group_by(Name) %>%
                       filter(row_number() ==1) %>%
                       gather("Region","Sales",c("NA_Sales","EU_Sales","JP_Sales","Other_Sales")) %>%
                       mutate(Region_updated = case_when(
                       Region == "NA_Sales" ~ "North America",
                       Region == "EU_Sales" ~ "Europe",
                       Region == "JP_Sales" ~ "Japan",
                       Region == "Other_Sales" ~ "Other",
                       TRUE ~ Region)) %>%
                       select(Name,Year,Genre,Region,Region_updated,Sales,meta_score,user_review)  %>% unique() %>% 
                       mutate(meta_tooltip = paste("Game:",Name,"\nYear:",Year,"\nRating:",meta_score,"\nRegion:",Region_updated,"\nSales:",Sales)) %>%
                       mutate(user_tooltip = paste("Game:",Name,"\nYear:",Year,"\nRating:",user_review,"\nRegion:",Region_updated,"\nSales:",Sales))

df <- data_set %>%  gather("Region","Sales",c("NA_Sales","EU_Sales","JP_Sales","Other_Sales")) %>%
                       mutate(Region_updated = case_when(
                       Region == "NA_Sales" ~ "North America",
                       Region == "EU_Sales" ~ "Europe",
                       Region == "JP_Sales" ~ "Japan",
                       Region == "Other_Sales" ~ "Other",
                       TRUE ~ Region)) %>% 
                       group_by(Name,Platform) %>% mutate(total_sales = sum(Sales)) %>%
                       filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
    
top_100 <- df %>% select(Name,total_sales) %>% unique() %>% arrange(desc(total_sales)) %>% head(n=100) %>%
  ungroup() %>%
  mutate(rank = row_number()) %>% select(-c("sales"))

df1 <- df %>% filter(Name %in% top_100$Name) %>% left_join(top_100,by="Name") %>% subset(rank %in% c(1.0:100.0))

df2 <- df %>% 
  select(Name, total_hours_watched, Sales,Region, avg_peak_channels, Genre) %>% 
  group_by(Name) %>% 
  mutate(all_sales = sum(Sales)) %>% 
  drop_na()

df2<- df2 %>% 
  select(Name, total_hours_watched, avg_peak_channels, all_sales, Genre,Region) %>% 
  unique()
```

Column {.sidebar}
-----------------------------------------------------------------------

### Filters

```{r}
checkboxGroupInput("fil_region","Choose Region:",c("North America"="NA_Sales",
                      "Europe" = "EU_Sales",
                      "Japan" = "JP_Sales",
                      "Other" = "Other_Sales"), selected = c("NA_Sales","EU_Sales","JP_Sales","Other_Sales"))

checkboxGroupInput("fil_genre","Choose Genre:",sort(unique(data_set$Genre)),selected= unique(data_set$Genre))
```

Column {.tabset}
-----------------------------------------------------------------------
### Bar Chart
```{r bar chart, echo=FALSE}
renderggiraph({
data_set2 <- data_set %>% gather("Region","Sales",c("NA_Sales","EU_Sales","JP_Sales","Other_Sales")) %>%
                       mutate(Region_updated = case_when(
                       Region == "NA_Sales" ~ "North America",
                       Region == "EU_Sales" ~ "Europe",
                       Region == "JP_Sales" ~ "Japan",
                       Region == "Other_Sales" ~ "Other",
                       TRUE ~ Region)) %>% mutate(tooltip = paste0('Genre:',Genre, '\n', 'Total Sales:', sum(Sales))) %>% filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
  
top_pub <- data_set2 %>% group_by(Publisher) %>% mutate(top_sales = sum(Sales)) %>%
           select(Publisher,top_sales) %>% unique() %>% arrange(desc(top_sales)) %>%
           head(n=5) %>% select(Publisher)

bar_data_set <- data_set2 %>% filter(Publisher %in% top_pub$Publisher)

bar_plot <- ggplot(bar_data_set,aes(x=Sales,y=Publisher,fill= Genre)) + labs(x = 'Sales', y = 'Publishers', title = 'Top Video Game Genres by Publishers') + scale_x_continuous(labels= scales::comma) + scale_color_brewer(palette="Set3") +
  geom_bar(stat = 'identity') +
  geom_point_interactive(aes(tooltip = tooltip), size = .05)

ggiraph(ggobj = bar_plot)

})
```

### point
```{r point, echo=FALSE}
df <- data_set %>%  gather("Region","Sales",c("NA_Sales","EU_Sales","JP_Sales","Other_Sales")) %>%
                       mutate(Region_updated = case_when(
                       Region == "NA_Sales" ~ "North America",
                       Region == "EU_Sales" ~ "Europe",
                       Region == "JP_Sales" ~ "Japan",
                       Region == "Other_Sales" ~ "Other",
                       TRUE ~ Region)) %>% 
                       group_by(Name,Platform) %>% mutate(total_sales = sum(Sales)) %>%
                       filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
    
top_100 <- df %>% select(Name,total_sales) %>% unique() %>% arrange(desc(total_sales)) %>% head(n=100) %>%
  ungroup() %>%
  mutate(rank = row_number()) %>% select(-c("sales"))

df1 <- df %>% filter(Name %in% top_100$Name) %>% left_join(top_100,by="Name") %>% subset(rank %in% c(1.0:100.0))

renderggiraph({
v1 <- df1 %>% 
  mutate(tooltip = paste0(tooltip = paste0('Title: ', stringr::str_to_title(Name), 
  '\nRank: ', rank, 
  '\nSales: ', Sales,
  '\nPlatform: ', Platform))) %>% 
ggplot(df1, mapping=aes(x = rank, y = total_sales/1000000, color = Platform, tooltip = tooltip)) +
  geom_point_interactive(size = 6, stat = "identity") +
  scale_x_reverse() +
  scale_color_brewer(palette = 'Set3') +
  theme_minimal() +
  labs(x = 'Rank', y = 'Global Sales in Millions', title = 'Global Sales of Top 100 Video Games') +
  theme(plot.title =element_text(hjust = .5, size = 18), text = element_text(size = 12))
ggiraph(ggobj = v1)
})
```

```{r bubble, echo=FALSE}
renderggiraph({
  viz2 <- df2 %>% 
    mutate(tooltip = paste0(tooltip = paste0('Title: ', stringr::str_to_title(Name), 
                                             '\nHours Watched On Twitch (Millions): ', total_hours_watched, 
                                             '\nSales (Millions): ', all_sales,
                                             '\nAverage Peak Channels: ', avg_peak_channels))) %>%
    ggplot(df2, mapping = aes(x = total_hours_watched/1000000, y=all_sales/1000000, size = avg_peak_channels, color = Genre, tooltip = tooltip)) +
    geom_point_interactive(alpha = .7) +
    scale_size(range = c(1.4, 20), name="Average Peak Channels") +
    labs(x = 'Hours Watched On Twitch in Millions', y = 'Sales in Millions', title = 'Hours Watched on Twitch to Sales') +
    scale_color_brewer(palette = 'Set3') +
    theme_minimal() +
    theme(plot.title = element_text(hjust = .5, size = 18), text = element_text(size = 12))
ggiraph(ggobj = viz2)
})


```


### Tree map

```{r tree map, echo=FALSE}
renderD3tree2({
tree_data_set <- data_set %>% select(-c("Platform","Rank")) %>% unique() %>%
                 gather("Region","Sales",c("NA_Sales","EU_Sales","JP_Sales","Other_Sales")) %>%
                 group_by(Name,Region) %>%
                 select(Name,Genre,Region,Sales) %>% mutate(Region_updated= Region) %>% unique() %>%
                  mutate(Region_updated = case_when(
                       Region == "NA_Sales" ~ "North America",
                       Region == "EU_Sales" ~ "Europe",
                       Region == "JP_Sales" ~ "Japan",
                       Region == "Other_Sales" ~ "Other",
                       TRUE ~ Region)) %>% filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
              
d3tree2(treemap(tree_data_set,index=c("Region_updated","Genre"),vSize="Sales",title= "Sales by Region and Genre"),rootname="Sales by Region and Genre")
})

```

### Reg Meta
```{r Reg Meta}
renderggiraph({
mscore_data_set <- regression_data_set %>% filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
                    

mscore <- ggplot(mscore_data_set,mapping= aes(x=meta_score,y=Sales)) + geom_point_interactive(aes(tooltip=meta_tooltip)) +
          geom_smooth() + scale_color_brewer(palette="Set3") + scale_y_continuous(labels= scales::comma) +
          labs(x="Metacritic Rating (1-100)",y= "Global Sales",title= "Metacritic Rating Regression on Global Sales")

ggiraph(ggobj=mscore)
})
```

### Reg User
```{r Reg User}
renderggiraph({
uscore_data_set <- regression_data_set %>% filter(Region %in% input$fil_region & Genre %in% input$fil_genre)
                  
uscore <- ggplot(uscore_data_set,mapping= aes(x=user_review,y=Sales)) + geom_point_interactive(aes(tooltip=user_tooltip)) + geom_smooth() + scale_color_brewer(palette="Set3") + scale_y_continuous(labels= scales::comma) +
          labs(x= "User Rating (1-100)",y= "Global Sales",title= "User Rating Regression on Global Sales")
ggiraph(ggobj=uscore)
})
```
